### ISSUE TITLE
cbox-theme causes 500 error on fresh install

### ISSUE THREAD

**Issue by rgilman** [cuny-academic-commons/cbox-theme#243] opened 2016-08-04 04:18 UTC
I'm trying to set up Commons In A Box in WP 4.5.3. I have the plugins all installed and activated including BuddyPress 2.6.1.1 and bbPress 2.5.10. When I activate cbox-theme I get a 500 server error. I'm happy to help with more info for the sake of debugging. Just let me know what would be helpful.

**Comment by boonebgorges** [comment] 2016-08-04 05:16
Hi Robert - Are you able to enable WP_DEBUG and share the error messages 
that show up? https://codex.wordpress.org/WP_DEBUG

**Comment by rgilman** [comment] 2016-08-04 05:59
Thanks for the clue. Enabling WP_DEBUG revealed that I had permissions errors that were preventing CBOX from creating various directories in uploads. I've fixed those and solved the 500 error but I still get the following non-fatal errors: (hope this helps – and thanks for all YOU do for WP and BP!)


Strict Standards: Static function ICE_Style_Property::create() should not be abstract in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/dom/style.php on line 825

Notice: bbp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 2.3.) in /home/robert/public_html/context/exp/wp-includes/functions.php on line 3897

Notice: bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). === Trace: #6 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/base/component.php(714): current_user_can('manage_options') #7 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/base/component.php(867): ICE_Component->check_caps() #8 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/base/registry.php(378): ICE_Component->supported() #9 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/base/registry.php(334): ICE_Registry->load_config_map('cbox_button_col...', Array) #10 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/components/options/registry.php(61): ICE_Registry->load_config_section('cbox_button_col...', Array) #11 /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/base/registry.php(316): ICE_Option_Registry->load_config in /home/robert/public_html/context/exp/wp-includes/functions.php on line 3897

Strict Standards: Non-static method ICE_Loader::load_wpadmin_lib() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/widgets/posts-list/class.php on line 251

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Strict Standards: Non-static method ICE_Files::list_filtered() should not be called statically, assuming $this from incompatible context in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/ext/options/ui/image-picker/class.php on line 82

Notice: The called constructor method for WP_Widget in CAC_Featured_Content_Widget is deprecated since version 4.3.0! Use
__construct()
instead. in /home/robert/public_html/context/exp/wp-includes/functions.php on line 3718

Notice: Undefined index: css_id in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/includes/menus.php on line 84

Strict Standards: Only variables should be passed by reference in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/dashboard/cpanel.php on line 35

Notice: Undefined offset: 2 in /home/robert/public_html/context/exp/wp-content/themes/cbox-theme/engine/ICE/components/options/component.php on line 552

**Comment by boonebgorges** [comment] 2016-08-04 13:46
@rgilman Glad it's up and running! Thanks for sharing the warnings - some are caused by cbox-theme, and  we're tracking them to be resolved in an upcoming release.

Please feel free to share any additional issues in new tickets. Thanks!

**Closed by boonebgorges** 2016-08-04 13:46 UTC
