### ISSUE TITLE
Blank screen when activating C-Box theme 1.0.7 no a fresh install

### ISSUE THREAD

**Issue by basemaly** [cuny-academic-commons/cbox-theme#193] opened 2014-04-21 18:05 UTC
I recently did a fresh install of WP 9 and Budyypress 2, to test whether how Commons-in-a-Box plugin and theme (1.0.7) would work. Unfortanately whenever I activate the C-Box theme I get a completely blank screen, and I can't figure out how to troubleshoot it. There doesn't seem to be anything in the httpd error log. Here's my site's URL: https://commonstage.pratt.edu and here's a preview link to the C-Box theme: https://commonstage.pratt.edu/?theme-preview=cbox-theme-1.0.7

Any ideas or suggestions would be hugely appreciated. Thanks.

**Comment by IKraljevic** [comment] 2015-11-09 02:06
Hi, have you found a solution for this problem?

(I  am seeing exactly the same problem as basemaly described, specifically I am getting the messages:

Strict Standards: Declaration of ICE_File_Cache::add() should be compatible with ICE_Map::add($key, $value, $prepend = false) in C:\Users\cik006\Documents\My Web Sites\wordpress\wp-content\themes\cbox-theme\engine\ICE\utils\file_cache.php on line 133

Strict Standards: Static function ICE_Style_Property::create() should not be abstract in C:\Users\cik006\Documents\My Web Sites\wordpress\wp-content\themes\cbox-theme\engine\ICE\dom\style.php on line 825

etc.)

Any reply will be much appreciated. Thanks

**Comment by r-a-y** [comment] 2015-11-09 21:54
The issue is related to having `WP_DEBUG` set to true in your dev environment.

To workaround this for now, see:
https://github.com/cuny-academic-commons/cbox-theme/issues/215#issuecomment-94040468

The code snippet linked in that comment will allow you to suppress these notices without turning `WP_DEBUG` off, which will allow you to activate the theme.

**Comment by IKraljevic** [comment] 2015-11-11 01:50
Thank you r-a-y, that worked perfectly!

**Comment by r-a-y** [comment] 2017-06-02 00:35
This should be fixed since v1.0.14.

**Closed by r-a-y** 2017-06-02 00:35 UTC
