### ISSUE TITLE
Responsive Issues with Mobile Menu

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/cbox-theme#176] opened 2013-11-27 01:49 UTC
Member Helene Finidori reports some mobile issues with the CBOX theme.

See the following link for the three issues found with the slider, the admin bar, and the menu:

http://commonsinabox.org/groups/help-support/forum/topic/issues-with-mobile-view-slider-menus/

**Comment by JonathanReeve** [comment] 2015-02-27 15:10
Possibly related issue from the forums: http://commonsinabox.org/groups/help-support/forum/topic/menus-disappear-in-mobile-devise/

**Comment by r-a-y** [comment] 2015-04-17 19:58
I've made a few commits to address the mobile menu being hidden behind the WP Toolbar.

You should now be able to see the mobile menu as it was intended at 768px and lower.  Going to close this one.

**Closed by r-a-y** 2015-04-17 19:58 UTC

**Comment by MrMaz** [comment] 2015-04-17 20:02
I made some tweaks to mobile stuff in my bleeding edge work, so I will
merge in your changes where applicable.

Marshall

**Comment by r-a-y** [comment] 2015-04-17 20:03
Cool, thanks Marshall!
